"""Manage one local Neo4j process per Pontis project.

This module is for Neo4j Community/local deployment where multi-database is not
available. It reads each project's graph.uri from pontis.yml and creates a
separate Neo4j runtime directory for that project:

  .neo4j/projects/<project>/{conf,data,logs,run,import}

Enterprise/single-process deployment does not need this script; use one shared
uri and distinct graph.database values in pontis.yml instead.
"""

from __future__ import annotations

import argparse
import os
import re
import signal
import shutil
import subprocess
import sys
import time
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from storage.config import ProjectConfig, load_config


TEXT2SQL_ROOT = ROOT.parent
PONTIS_WORKSPACE = TEXT2SQL_ROOT / "workspace" / "baselines" / "pontis"

DEFAULT_BASE_DIR = PONTIS_WORKSPACE / "neo4j" / "projects"
DEFAULT_ENV_FILE = PONTIS_WORKSPACE / "neo4j" / "neo4j.env"
DEFAULT_HTTP_BASE = 7474
DEFAULT_BOLT_BASE = 7687


def _load_local_env(env_file: Path) -> dict[str, str]:
    env = dict(os.environ)
    if not env_file.exists():
        return env
    for line in env_file.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export "):]
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("'\"")
        value = value.replace("$PATH", env.get("PATH", ""))
        value = value.replace("${PATH}", env.get("PATH", ""))
        env[key] = value
    return env


def _safe_name(name: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", name.strip())
    return safe or "project"


def _parse_bolt_uri(uri: str) -> tuple[str, int]:
    parsed = urlparse(uri or "")
    if parsed.scheme not in {"bolt", "neo4j"}:
        raise ValueError(f"Only bolt:// or neo4j:// graph.uri is supported: {uri!r}")
    host = parsed.hostname or "localhost"
    port = parsed.port or DEFAULT_BOLT_BASE
    return host, port


def _listen_host(host: str) -> str:
    if host in {"localhost", "127.0.0.1"}:
        return "127.0.0.1"
    return host


def _http_port_for_bolt(bolt_port: int) -> int:
    return DEFAULT_HTTP_BASE + (bolt_port - DEFAULT_BOLT_BASE)


def _project_dir(base_dir: Path, project: str) -> Path:
    return base_dir / _safe_name(project)


def _pid_file(base_dir: Path, project: str) -> Path:
    return _project_dir(base_dir, project) / "run" / "pontis-neo4j.pid"


def _read_pid(base_dir: Path, project: str) -> int | None:
    path = _pid_file(base_dir, project)
    try:
        return int(path.read_text().strip())
    except Exception:
        return None


def _pid_running(pid: int | None) -> bool:
    if not pid:
        return False
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    return True


def _copy_log_configs(neo4j_home: Path, conf_dir: Path):
    source_conf = neo4j_home / "conf"
    if not source_conf.exists():
        return
    for xml in source_conf.glob("*.xml"):
        target = conf_dir / xml.name
        if not target.exists():
            shutil.copy2(xml, target)


def _write_instance_config(
    project: str,
    config: ProjectConfig,
    base_dir: Path,
    env: dict[str, str],
    heap_initial: str,
    heap_max: str,
    pagecache: str,
) -> Path:
    host, bolt_port = _parse_bolt_uri(config.graph.uri)
    listen_host = _listen_host(host)
    http_port = _http_port_for_bolt(bolt_port)

    root = _project_dir(base_dir, project)
    conf_dir = root / "conf"
    data_dir = root / "data"
    logs_dir = root / "logs"
    run_dir = root / "run"
    import_dir = root / "import"
    for path in (conf_dir, data_dir, logs_dir, run_dir, import_dir):
        path.mkdir(parents=True, exist_ok=True)

    neo4j_home = Path(env.get("NEO4J_HOME", "")).expanduser()
    if neo4j_home:
        _copy_log_configs(neo4j_home, conf_dir)

    conf = conf_dir / "neo4j.conf"
    conf.write_text(
        "\n".join([
            f"# Generated by storage.neo4j.instances for {project}",
            "initial.dbms.default_database=neo4j",
            f"server.directories.data={data_dir}",
            f"server.directories.logs={logs_dir}",
            f"server.directories.run={run_dir}",
            f"server.directories.import={import_dir}",
            "server.bolt.enabled=true",
            f"server.bolt.listen_address={listen_host}:{bolt_port}",
            "server.http.enabled=true",
            f"server.http.listen_address={listen_host}:{http_port}",
            "server.https.enabled=false",
            "dbms.security.auth_enabled=false",
            f"server.memory.heap.initial_size={heap_initial}",
            f"server.memory.heap.max_size={heap_max}",
            f"server.memory.pagecache.size={pagecache}",
            "dbms.memory.transaction.total.max=64m",
            "dbms.usage_report.enabled=false",
            "",
        ]),
        encoding="utf-8",
    )
    return conf_dir


def _command_env(conf_dir: Path, env: dict[str, str]) -> dict[str, str]:
    out = dict(env)
    out["NEO4J_CONF"] = str(conf_dir)
    neo4j_home = out.get("NEO4J_HOME")
    java_home = out.get("JAVA_HOME")
    path_parts = []
    if neo4j_home:
        path_parts.append(str(Path(neo4j_home) / "bin"))
    if java_home:
        path_parts.append(str(Path(java_home) / "bin"))
    path_parts.append(out.get("PATH", ""))
    out["PATH"] = os.pathsep.join(p for p in path_parts if p)
    return out


def _run(cmd: list[str], env: dict[str, str], quiet: bool = False) -> int:
    stdout = subprocess.DEVNULL if quiet else None
    stderr = subprocess.DEVNULL if quiet else None
    return subprocess.run(cmd, env=env, stdout=stdout, stderr=stderr).returncode


def _start_console(project: str, conf_env: dict[str, str], base_dir: Path, grace_seconds: float) -> int:
    root = _project_dir(base_dir, project)
    log_path = root / "logs" / "console.log"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    log_file = log_path.open("ab")
    proc = subprocess.Popen(
        ["neo4j", "console"],
        cwd=str(ROOT),
        env=conf_env,
        stdout=log_file,
        stderr=subprocess.STDOUT,
        start_new_session=True,
    )
    _pid_file(base_dir, project).write_text(str(proc.pid), encoding="utf-8")
    if grace_seconds > 0:
        time.sleep(grace_seconds)
        if proc.poll() is not None:
            print(f"{project}: Neo4j exited during startup, see {log_path}", file=sys.stderr)
            return proc.returncode or 1
    return 0


def _stop_pid(project: str, base_dir: Path, timeout_seconds: float) -> bool:
    pid = _read_pid(base_dir, project)
    path = _pid_file(base_dir, project)
    if not _pid_running(pid):
        path.unlink(missing_ok=True)
        return False
    assert pid is not None
    try:
        os.killpg(pid, signal.SIGTERM)
    except ProcessLookupError:
        path.unlink(missing_ok=True)
        return False
    deadline = time.time() + timeout_seconds
    while time.time() < deadline:
        if not _pid_running(pid):
            path.unlink(missing_ok=True)
            return True
        time.sleep(0.2)
    try:
        os.killpg(pid, signal.SIGKILL)
    except ProcessLookupError:
        pass
    path.unlink(missing_ok=True)
    return True


def _needs_initial_password(base_dir: Path, project: str) -> bool:
    data_dir = _project_dir(base_dir, project) / "data"
    return not (data_dir / "databases" / "system").exists()


def _ensure_initial_password(project: str, conf_env: dict[str, str], base_dir: Path):
    password = conf_env.get("NEO4J_PASSWORD", "")
    if not password or not _needs_initial_password(base_dir, project):
        return
    code = _run(
        ["neo4j-admin", "dbms", "set-initial-password", password],
        env=conf_env,
        quiet=False,
    )
    if code != 0:
        raise RuntimeError(f"Failed to set initial Neo4j password for {project}")


def _projects_from_args(all_projects: dict[str, ProjectConfig], names: list[str], all_flag: bool) -> list[str]:
    if all_flag:
        return list(all_projects.keys())
    if names:
        missing = [name for name in names if name not in all_projects]
        if missing:
            raise KeyError(f"Unknown project(s): {', '.join(missing)}")
        return names
    raise ValueError("Specify project names or --all")


def _load(args) -> tuple[dict[str, ProjectConfig], dict[str, str], Path]:
    config = load_config(args.config)
    env = _load_local_env(Path(args.env_file))
    base_dir = Path(args.base_dir).expanduser()
    return config.projects, env, base_dir


def cmd_list(args) -> int:
    projects, _, _ = _load(args)
    for name, config in projects.items():
        uri = config.graph.uri or os.environ.get("NEO4J_URI", "bolt://localhost:7687")
        database = config.graph.database or "neo4j"
        print(f"{name}\t{uri}\tdatabase={database}")
    return 0


def cmd_render(args) -> int:
    projects, env, base_dir = _load(args)
    for name in _projects_from_args(projects, args.projects, args.all):
        conf_dir = _write_instance_config(
            name,
            projects[name],
            base_dir,
            env,
            args.heap_initial,
            args.heap_max,
            args.pagecache,
        )
        print(f"{name}\t{conf_dir / 'neo4j.conf'}")
    return 0


def cmd_start(args) -> int:
    projects, env, base_dir = _load(args)
    for name in _projects_from_args(projects, args.projects, args.all):
        config = projects[name]
        database = config.graph.database or "neo4j"
        if database != "neo4j":
            print(
                f"{name}: graph.database={database!r}; multi-process Community mode expects database='neo4j'",
                file=sys.stderr,
            )
            return 2
        conf_dir = _write_instance_config(
            name,
            config,
            base_dir,
            env,
            args.heap_initial,
            args.heap_max,
            args.pagecache,
        )
        conf_env = _command_env(conf_dir, env)
        if _pid_running(_read_pid(base_dir, name)):
            print(f"{name}\talready running")
            continue
        _ensure_initial_password(name, conf_env, base_dir)
        code = _start_console(name, conf_env, base_dir, args.start_grace)
        if code != 0:
            return code
        print(f"{name}\tstarted\t{config.graph.uri}")
    return 0


def cmd_stop(args) -> int:
    projects, env, base_dir = _load(args)
    for name in _projects_from_args(projects, args.projects, args.all):
        conf_dir = _write_instance_config(
            name,
            projects[name],
            base_dir,
            env,
            args.heap_initial,
            args.heap_max,
            args.pagecache,
        )
        _command_env(conf_dir, env)
        stopped = _stop_pid(name, base_dir, args.stop_timeout)
        if not stopped:
            print(f"{name}\tnot running")
        else:
            print(f"{name}\tstopped")
    return 0


def cmd_status(args) -> int:
    projects, env, base_dir = _load(args)
    failed = 0
    for name in _projects_from_args(projects, args.projects, args.all):
        conf_dir = _write_instance_config(
            name,
            projects[name],
            base_dir,
            env,
            args.heap_initial,
            args.heap_max,
            args.pagecache,
        )
        _command_env(conf_dir, env)
        if _pid_running(_read_pid(base_dir, name)):
            print(f"{name}\trunning\t{projects[name].graph.uri}")
        else:
            print(f"{name}\tstopped\t{projects[name].graph.uri}")
            failed = 3
    return failed


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["list", "render", "start", "stop", "restart", "status"])
    parser.add_argument("projects", nargs="*", help="Project names from pontis.yml")
    parser.add_argument("--all", action="store_true", help="Apply command to all configured projects")
    parser.add_argument("--config", default=str(ROOT / "pontis.yml"), help="Pontis config path")
    parser.add_argument("--env-file", default=str(DEFAULT_ENV_FILE), help="Neo4j env file")
    parser.add_argument("--base-dir", default=str(DEFAULT_BASE_DIR), help="Directory for per-project Neo4j runtimes")
    parser.add_argument("--heap-initial", default="128m")
    parser.add_argument("--heap-max", default="256m")
    parser.add_argument("--pagecache", default="64m")
    parser.add_argument("--start-grace", type=float, default=2.0, help="Seconds to wait for immediate startup failure")
    parser.add_argument("--stop-timeout", type=float, default=20.0, help="Seconds to wait before SIGKILL")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        if args.command == "list":
            return cmd_list(args)
        if args.command == "render":
            return cmd_render(args)
        if args.command == "start":
            return cmd_start(args)
        if args.command == "stop":
            return cmd_stop(args)
        if args.command == "status":
            return cmd_status(args)
        if args.command == "restart":
            stop_code = cmd_stop(args)
            start_code = cmd_start(args)
            return start_code or (0 if stop_code in {0, 3} else stop_code)
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
